language: python
python:
- '2.7'
env:
  global:
  - secure: H4RMbyq7lTQlJsOaH/VBv9qW+DiahWx7GrPuTUHqidbfV9k8oFSp44SIsMrvgmuiRUOmdjeeUng0FFOfaKN5fZ3djp4ZJNHFN/m1ClDEoNidi5767OJKgK42V2DHbqEeFl2K+ktx7lsb3fB4+bVVFEU+IouyTLqNdNBEO6hhjd4i10XGm+0lwqvDdXwtOG6q6B86X1W+37wfpBa+CVZZZBVTXTxEa9WsBEpJgtpBwUddvszC2OvUwu+b2zMbwWmGUPU1Xly0HxdmyhQ9UOcHNYQLptO0kVRm+impcwuRxwOwhEi/LICFvJxz+bh7U1VEf3Si+mWN6i82eHbS532/F0cHNwHEQPA1+xJn0MPmh/y1OHXlKFOKy/gaqSAnz1gJ419PBcBIOjTyQp1iie20l+/Ap29UzRN6HRDyOW/jDG8hZALtKC99edYXspAfDFDedDUcN5bGN8KrNtfq7Lsdc8sN1+/9ioiHkGjUZCMWq13aHcmwcZKjf3W+l69oRO/Cx10tjZTZGtBmlxWtcHj4X1QSaF5u42YCgcxXPP8P3gKHT07TR+LgBZfwMZ2yJBql36p9dbkqDf4ZYbLIycKGM22i8Ex1EmZn6x9rLFPWKs8M8AFm29cYkxuL0Ke4ZKi3iuPgnwIiHlG1blXxzEfc3FVA2nE+YDh+yKo2ZNa+RhQ=
  matrix:
  - QUILT_URL="https://quiltdata.com"
  - QUILT_URL="https://quilt-heroku.herokuapp.com"
before_install: pip install pytest pytest-cov
install: pip install -r requirements.txt
script: python -m pytest --cov=quilt/ tests
after_success: bash <(curl -s https://codecov.io/bash)
