language: python
python:
- '2.7'
env:
  global:
    secure: H2dD3a0D/0Ky53jHvINmo9bVHrBH3SLkfJaGoGeUprYSptoEG9ZdL4IqAGpKWJJYRvoOd84QjTEAVPcQqaUGwckJnj0uUxEXDiNv0OdyvMPr8csbhz44FWUquYM8hPrmBoJffsnSosgF6nmH0V1BqFoDfVJ4Ihy5Rabe62UuQwr1/S1XkbLt8YwnhVfcVMJ04VdgfVvi6NdblH7RDMafYf8K65p/JjQh48cVCkfukpY/qWELAU4Hz9BBzYUQmXbwyhCeRGG4Knh/pAZE6o9t4xARyuAs1gKbf6SMounDYOnI8m9GzuhHmxh7WUc7PkZfcSrnQcs8WIDuhszmIZRqIotajic1snyrhn3H1A0ayoL1GGPpo10L/ctOhNpeP/u4DwGrFV5lJqLXcRAze0p2+8IvDcN1cUo5f5+rQglCk5qNHyDDMQzZYdbgaMdCBpWJkB4Rodtqy4Zg/Fxm3vvsJwg4WsjeK3YoBLmCq9uZShukPK+mHwgo+UPuq/tI2otZSPPaxvIbLfe2FmHjPMp7sCpUrKEVvXKkPM5ju/7RFV2AA5AgSnV7l+6kwYeKAS0VXxZ7Tyzrl0A7P8zpMHKIB95ptkneu1g0Kdtn/cUBbFUJAbN2S2sILMKTcYXW6yBCDQm2pxdmQ6I+Xs0z15WgWlFCvloc8kE+hhaTca7M7h0=
  matrix:
  - QUILT_URL="https://quiltdata.com"
  - QUILT_URL="https://quilt-heroku.herokuapp.com"
before_install: pip install pytest pytest-cov
install: pip install -r requirements.txt
script: python -m pytest --cov=quilt/ tests
after_success: bash <(curl -s https://codecov.io/bash)
